### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by fanrunqi** [xzhflying/fuzzy-ninja#37]
可以邀请我加入 川大 组织吗？ 本人 研二 计算机 ，谢谢！

**Comment by xzhflying** [comment]
@fanrunqi 你好，你是说我所在的scuol吗？首先我并不具备邀请加入组织的权限，你可以尝试申请加入。其次，这个组织主要目的是为了本科阶段之前举办的几次Facebook Open Academy项目的交流和Github使用练习，并没有什么实质的内容。不过也希望能有一个可以一起交流学习的平台。

**Comment by fanrunqi** [comment]
o 那算了，反正没什么用不是
